### ISSUE TITLE
SSL certificate error when accessing https://www

### ISSUE THREAD

**Issue by martinmorando** [amardeshbd/hossainkhan.com#37]
Hossain, I read [your article ](https://medium.com/@hossainkhan/using-custom-domain-for-github-pages-86b303d3918a) on how to use a custom domain for GitHub Pages and I am using it for my websites.

It works mostly good for a minor exception. When trying to access the site with _https://www_. **https://www.hossainkhan.com/** the browser shows a big warning. At least Firefox. This is part of the message:

> 

**Warning: Potential Security Risk Ahead**

Firefox detected a potential security threat and did not continue to www.hossainkhan.com. If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details.....

Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for www.hossainkhan.com. The certificate is only valid for the following names: www.github.com, *.github.io, *.githubusercontent.com, *.github.com, github.com, github.io, githubusercontent.com

Error code: SSL_ERROR_BAD_CERT_DOMAIN

> 

I have the same problem and I didn't find the solution yet. GitHub Pages documentation on how to do this is not clear. Already contacted GitHub support 1 day ago but no answer yet. Maybe changing the repository to xxxx.github.io?

**Comment by amardeshbd** [comment]
@martinmorando That is a good find. The security error is actually unacceptable at this age of web.
This error is also visible in Chrome. 

I don't know the solution at the moment, I will google it and also try to contact github support and update it here and in the article.

**Comment by amardeshbd** [comment]
Checked that if you try `www.hossainkhan.com`, then github auto redirects to **HTTPS** due to settings in the repo. However, this does not solve the actual issue in case someone manually puts it.

**Comment by amardeshbd** [comment]
I'm not sure if the allowed domain list is actually an issue. Because none of the custom domain falls under that. Usually before custom domain the project URL is like `https://amardeshbd.github.io/repo-name/` or in my case https://amardeshbd.github.io/hossainkhan.com/

![Screen Shot 2020-02-13 at 23 54 59](https://user-images.githubusercontent.com/99822/74502789-a2c72600-4ebc-11ea-9219-853dfb23779c.png)
<img width="1162" alt="Screen Shot 2020-02-13 at 11 53 32 PM" src="https://user-images.githubusercontent.com/99822/74502804-aeb2e800-4ebc-11ea-9bba-c715cc9f6c7b.png">

**Comment by amardeshbd** [comment]
@martinmorando did you enforce HTTPS?
https://help.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https

**Comment by martinmorando** [comment]
@amardeshbd I contacted  support. This is what Steve Graff, GitHub Developer Support, answered (I'm sharing with his permission):

> Thanks for reaching out about this! We don't currently support creating a certificate that covers both your root domain and your www subdomain. We only generate a certificate for the exact domain that you specify in the custom domain input box. I will add your +1 to that feature request internally though!
If you've set up a CNAME record for the www subdomain that points to your GitHub.io address username.github.io then we will redirect traffic from the www subdomain to your apex domain, but only if you use a protocol-less, or http://, link. If you explicitly specify https://www.example.com you will still encounter a certificate error.

So, there's nothing we can do about it as long as we keep using GitHub Pages. Maybe you can reach them out so they add another +1 to that feature. 

P.D: I had disabled "enforce HTTPS" on that website temporarily. Now I activated again, thanks for the reminder.

**Comment by amardeshbd** [comment]
hi @martinmorando I got a similar response from Simon. Looks like nothing can be done at the moment.
Just need to make sure, the explicit `https://www` URL does not leak out in the web, in that way this should not be an issue.

> Simon Giesemann (GitHub Developer Support)
> Feb 14, 5:28 AM UTC
> 
> Hi Hossain,
> Thanks for reaching out about this! We don't currently support creating a certificate that covers both your root domain and your www subdomain. We only generate a certificate for the exact domain that you specify in the custom domain input box. I will add your +1 to that feature request internally though!
> 
> If you've set up a CNAME record for the www subdomain that points to your GitHub.io address username.github.io then we will redirect traffic from the www subdomain to your apex domain, but only if you use a protocol-less, or http://, link. If you explicitly specify https://www.example.com you will still encounter a certificate error.
> 
> Cheers,
> Simon
> GitHub Support

**Comment by martinmorando** [comment]
Exactly, otherwise it would negatively impact on SEO. We can close this issue on your repository if you agree.
